
services:
  db:
    image: postgres:16
    container_name: postgres-db2
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: goLANGn1nja
      POSTGRES_DB: postgres
    volumes:
      - ./schema/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped